import Head from 'next/head'
import BookmarkListItem from '../components/BookmarkListItem'
import Navigation from '../components/Navigation'
import { MagnifyingGlassIcon } from '@heroicons/react/24/outline'


export default function Home() {
  return (
    <>
      <Head>
        <title>Estoril</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-8 flex justify-around bg-slate-100 h-screen">
        <Navigation/>
        <section className='flex flex-col space-y-4'>
          <button type="button" className="flex w-full items-center space-x-3 text-sm tracking-wide text-slate-400 px-4 h-10 bg-white shadow-sm text-left rounded-lg ring-1 ring-slate-900/10 hover:ring-slate-300 focus:outline-none focus:ring-2 focus:ring-sky-500">
            <MagnifyingGlassIcon className='w-4 h-4'/>
            <span>Search</span>
          </button>
          <BookmarkListItem/>
        </section>
        <span>Spacer</span>
      </main>
    </>
  )
}
